import { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { FC, PropsWithChildren } from "react";

import { NavBar } from "@/components/NavBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<Readonly<PropsWithChildren>> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-950 text-white`}>
        <NextTopLoader showSpinner={false} />
        <NavBar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
